[package]
name = "actors-example"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.12"
ockam = { version = "0.41", no-default-features = true, features = ["std"] }
serde = { version = "1.0", features = ["derive"] }