image: ubuntu:latest

before_script:
  - apt-get update && apt-get upgrade -y
  - apt-get install -y emacs tree
  - emacs --batch -l ci/setup.el

deep-dive-async:
    stage: build
    script:
      - cd dd-async/
      - emacs --batch -l ../ci/export-course.el